name: mindbox
description: Flutter Mindbox SDK. Plugin wrapper over of Mindbox iOS/Android SDK.
version: 2.2.0
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-moscow/flutter-sdk/tree/master/mindbox

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mindbox_android
      ios:
        default_package: mindbox_ios

dependencies:
  flutter:
    sdk: flutter
  mindbox_android: ^2.2.0
  mindbox_ios:
    git:
     url: https://github.com/mindbox-cloud/flutter-sdk.git
     path: mindbox_ios
     ref: 4eb0e61b409d1e3ad0174bc47d096cd45d03cc79
  mindbox_platform_interface: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
