name: publish

on:
  push:
    branches:
      - master

jobs:

  flutter_test:
    name: ${{ matrix.package }} running analyze and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - 'mindbox'
          - 'mindbox_android'
          - 'mindbox_ios'
          - 'mindbox_platform_interface'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: cd ${{ matrix.package }} && flutter pub get
      - run: cd ${{ matrix.package }} && flutter analyze
      - run: cd ${{ matrix.package }} && flutter test

  publish:
    needs: [flutter_test]
    timeout-minutes: 4
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} publishing
    strategy:
      matrix:
        package:
          - 'mindbox'
          - 'mindbox_android'
          - 'mindbox_ios'
          - 'mindbox_platform_interface'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 2

      - name: Check package Pubspec
        id: pubspec
        run: |
          set +e
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '${{ matrix.package }}/pubspec.yaml'
          echo ::set-output name=changed::$?
          set -e
      - name: Extract package version
#        if: steps.pubspec.outputs.changed == 0
        run: |
          cd ${{ matrix.package }}
          echo "VERSION=$(awk '{if ($1 ~ /^version:/) print $2}' pubspec.yaml)" >> $GITHUB_ENV
      - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
#        if: steps.pubspec.outputs.changed == 0
        with:
          package_directory: ${{ matrix.package }}
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true
      - name: Create Release
#        if: steps.pubspec.outputs.changed == 0
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.package }}-v${{ env.VERSION }}
          release_name: ${{ matrix.package }} v${{ env.VERSION }}
          draft: false
          prerelease: false
